enum CitiesEnum {
    PRISHTINA = 'Prishtina',
    PRIZREN = 'Prizren',
    PEJA = 'Peja',
    GJAKOVA = 'Gjakova',
    GJILAN = 'Gjilan',
    FERIZAJ = 'Ferizaj',
    MITROVICA = 'Mitrovica',
    PODUJEVA = 'Podujeva',
    VUSHTRRI = 'Vushtrri',
    SUHAREKA = 'Suhareka',
    RAHOVEC = 'Rahovec',
    MALISHEVA = 'Malisheva',
    LIPJAN = 'Lipjan',
    DRENAS = 'Drenas',
    ISTOG = 'Istog',
    KAMENICA = 'Kamenica',
    VITIA = 'Vitia',
    SKENDERAJ = 'Skenderaj',
    DECAN = 'Decan',
    KLINE = 'Klinë',
    DRAGASH = 'Dragash',
    FUSHE_KOSOVE = 'Fushë Kosovë',
    KACANIK = 'Kaçanik',
    SHTIME = 'Shtime',
    OBILIQ = 'Obiliq',
    LEPOSAVIQ = 'Leposaviq',
    ZVECAN = 'Zveçan',
    ZUBIN_POTOK = 'Zubin Potok',
    NOVOBERDE = 'Novobërdë',
    JUNIK = 'Junik',
    HANI_I_ELEZIT = 'Hani i Elezit',
    MAMUSHE = 'Mamushë',
    GRACANICE = 'Graçanicë',
    RANILLUG = 'Ranillug',
    PARTESH = 'Partesh',
    KLLOKOT = 'Kllokot'
}

export default CitiesEnum;