const cities = [
    'Pristina',
    'Prizren',
    'Peja',
    'Gjakova',
    'Gjilan',
    'Ferizaj',
    'Mitrovica',
    'Podujeva',
    'Vushtrri',
    'Suhareka',
    'Rahovec',
    'Malisheva',
    'Lipjan',
    'Drenas',
    'Istog',
    'Kamenica',
    'Vitia',
    'Skenderaj',
    'Decan',
    'Klinë',
    'Dragash',
    'Fushë Kosovë',
    'Kaçanik',
    'Shtime',
    'Obiliq',
    'Leposaviq',
    'Zubin Potok',
    'Zveçan',
    'Novobërdë',
    'Junik',
    'Hani i Elezit',
    'Mamushë',
    'Graçanicë',
    'Ranillug',
    'Partesh',
    'Kllokot'
]

export default cities;