
enum NotificationTypesEnum {
    ORDER_CREATED = 'ORDER_CREATED',
    ORDER_CONFIRMED = 'ORDER_CONFIRMED',
    ORDER_SHIPPED = 'ORDER_SHIPPED',
    ORDER_DELIVERED = 'ORDER_DELIVERED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',

    ITEM_SOLD = 'ITEM_SOLD',

    REVIEW_RECEIVED = 'REVIEW_RECEIVED',

    SYSTEM = 'SYSTEM'
};

export default NotificationTypesEnum;