
enum NotificationTypesEnum {
    ORDER_SHIPPED = 'ORDER_SHIPPED',
    ORDER_RECEIVED = 'ORDER_RECEIVED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',

    HIGHER_BID_ALERT = "HIGHER_BID_ALERT",
    BID_ACCEPTED = "BID_ACCEPTED",

    REVIEW_RECEIVED = 'REVIEW_RECEIVED'
};

export default NotificationTypesEnum;